# permissions for end users to edit automountmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: automountmap-editor-role
rules:
- apiGroups:
  - autofs.example.com.example.com
  resources:
  - automountmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autofs.example.com.example.com
  resources:
  - automountmaps/status
  verbs:
  - get
